image: Visual Studio 2017

platform:
- x86
- x64

install:
  - ps: Install-Product node LTS $env:platform;
  - cmd: npm install -g node-gyp
  - ps: node -v
  - ps: npm -v
  - ps: node-gyp -v
  - cmd: yarn install --frozen-lockfile
  - cmd: yarn test
  - ps: $publish_binary = 0
  - ps: if ($env:appveyor_repo_tag -match "true") { $publish_binary=1; }
  - ps: echo "tag $env:appveyor_repo_tag_name branch $env:APPVEYOR_REPO_BRANCH"
build_script:
  - ps: echo "publish $publish_binary"
  - ps: $arch = $env:platform
  - ps: if ($arch -match "x86") { $arch="ia32"; }
  - ps: |
      if ($publish_binary -Eq "1") {
        yarn global add prebuild 2>&1 | write-host
        prebuild -t 11.15.0 -t 12.7.0 -t 13.0.0 -r node --upload $env:prebuild_upload 2>&1 | write-host
        prebuild -t 5.0.0 -t 6.0.0 -t 7.0.0 -t 8.0.0 -r electron --upload $env:prebuild_upload 2>&1 | write-host
      }
      echo "done."
